name: retroarch
adopt-info: retroarch  # define the version at `retroarch` part
title: RetroArch
summary: RetroArch is the official reference frontend for the libretro API.
description: |
  The official reference frontend for the libretro API.

  RetroArch provides a variety of advanced user-facing features and powerful configuration capabilities to programs that target the libretro API. While a majority of these programs are emulators for retro gaming consoles, various gaming engines and other multimedia applications are also represented. The programs, known as "cores", can be downloaded and updated directly from RetroArch's built-in Online Updater.

  RetroArch defaults to a gamepad-friendly 10-foot/leanback interface that is perfect for use with living-room and home theater PCs, but there is also a more traditional keyboard-and-mouse interface available by pressing F5.

  RetroArch is written in portable C and licensed GPLv3.
license: GPL-3.0
icon: snap/gui/retroarch.svg
confinement: strict
grade: stable
platforms:
  amd64:
  armhf:
  arm64:
  ppc64el:
base: core24

plugs:
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404
  shared-memory:  # Required by some cores such as dolphin-libretro and swanstation-libretro
    private: true

layout:
  /usr/share/X11/XErrorDB:
    symlink: $SNAP/gpu-2404/X11/XErrorDB

apps:
  retroarch:
    command-chain:
    - bin/gpu-2404-wrapper
    - bin/retroarch.wrapper
    command: usr/local/bin/retroarch
    environment: &_environment
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/blas:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/lapack
      QT_PLUGIN_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/qt6/plugins
    plugs: &_plugs
      - network
      - network-bind
      - x11
      - opengl
      - home
      - alsa
      - audio-playback
      - bluez
      - joystick
      - raw-usb
      - removable-media
      - wayland
      - unity7
      - desktop
      - desktop-legacy
      - screen-inhibit-control
      - hardware-observe
      - mount-observe
      - camera
  daemon:
    command-chain:
    - bin/daemon-start.sh
    - bin/gpu-2404-wrapper
    - bin/retroarch.wrapper
    command: usr/local/bin/retroarch -f -v
    daemon: simple
    restart-delay: 3s
    restart-condition: always
    environment: *_environment
    plugs: *_plugs

parts:
  retroarch-wrapper:
    plugin: dump
    source: scripts
    stage-packages:
      - inotify-tools
  retroarch:
    plugin: autotools
    source-type: git
    source: https://github.com/libretro/RetroArch.git
    #source-branch: steamdeck                                 # To build from a non-default branch
    #source-tag: v1.20.0                                      # To build from a tag
    #source-commit: ab3b175848fa6cd8b2340809631e30bc0fe1d136  # Requires the full 40-character SHA-1
    after: [retroarch-wrapper]
    build-environment:
      - MAKEFLAGS: HAVE_BUILTINZLIB=0 HAVE_ZLIB_COMMON=1
    autotools-configure-parameters:
      - --enable-kms
      - --enable-xvideo
      - --enable-ffmpeg
      - --enable-ssa
      - --disable-coreaudio
      - --enable-jack
      - --enable-pulse
      - --disable-roar
      - --disable-rsound
      - --disable-sdl
      - --enable-sdl2
      - --disable-vg
      - --disable-v4l2
      - --disable-xinerama
      - --enable-qt
      - --enable-vulkan
      - --enable-discord
      - --enable-dbus
    stage-packages:
      - libnotify-bin
      - fonts-dejavu-core
      - freeglut3-dev
      - libasound2t64
      - libavcodec60
      - libavformat60
      - libavutil58
      - libfreetype6
      - libgbm1
      - libjack-jackd2-0
      #- libpipewire-0.3-dev
      - libminizip1t64
      - libopenal1
      - libpulse0
      - libswresample4
      - libswscale7
      - libudev1
      - libusb-1.0-0
      - libxrandr-dev
      - libxext6
      - libxinerama1
      - libxkbcommon0
      - libxv1
      - zlib1g
      - libqt6core6t64
      - libqt6gui6t64
      - libqt6widgets6t64
      - libqt6concurrent6t64
      - libqt6network6t64
      - qt6-wayland
      - libstdc++6
      - libgcc1
      - liblzma5
      - libbz2-1.0
      - libpcre3
      - libsystemd0
      - libass9
      - libfribidi0
      - libsdl1.2debian
      - libsdl-net1.2
      - libbluetooth3
      - libxi6
      - libaio1t64
      - libdecor-0-0
      - libdecor-0-plugin-1-cairo
      - libsdl2-2.0-0
      - libdbus-1-3
      - libavdevice60
      - libblas3
    build-packages:
      - gcc
      - make
      - libasound2-dev
      - libass-dev
      - libavcodec-dev
      - libavdevice-dev
      - libavformat-dev
      - libdrm-dev
      - libegl1-mesa-dev
      - libfreetype6-dev
      - libgbm-dev
      - libgl1-mesa-dev
      - libjack-jackd2-dev
      - libpulse-dev
      - libswscale-dev
      - libusb-1.0-0-dev
      - libudev-dev
      - libx11-xcb-dev
      - libxml2-dev
      - libxv-dev
      - mesa-common-dev
      - xserver-xorg-input-all
      - zlib1g-dev
      - libvulkan-dev
      - libxxf86vm-dev
      - libdbus-1-dev
      - libdecor-0-dev
      - libsdl2-dev
      - qt6-base-dev
      - qmake6-bin
    override-pull: |
      craftctl default
      tag=$(git describe --tags --abbrev=0)
      count=$(git rev-list $tag.. --count)
      if [ "$count" = 0 ];
      then
        version=${tag:1}
      else
        hash=$(git rev-parse --short=7 HEAD)
        version=${tag:1}+git${count}.${hash}
      fi
      craftctl set version=$version
  retroarch-filters:
    plugin: autotools
    after: [retroarch]
    source: https://github.com/libretro/RetroArch.git
    source-type: git
    override-build: |
      pushd libretro-common/audio/dsp_filters/ && ./configure && make && make install DESTDIR=$CRAFT_PART_INSTALL/.config/filters/audio INSTALLDIR= && popd
      pushd gfx/video_filters/ && ./configure && make && make install DESTDIR=$CRAFT_PART_INSTALL/.config/filters/video INSTALLDIR= && popd
    stage:
      - .config/filters/video
      - .config/filters/audio
  retroarch-assets:
    plugin: dump
    after: [retroarch-wrapper]
    source: https://github.com/libretro/retroarch-assets/archive/master.tar.gz
    source-type: tar
    organize:
      xmb: .config/assets/xmb/
      glui: .config/assets/glui/
      rgui: .config/assets/rgui/
      ozone: .config/assets/ozone/
      sounds: .config/assets/sounds/
      menu_widgets: .config/assets/menu_widgets/
    stage: &_assets
    - -configure
    - -Makefile
    - .config/assets/menu_widgets/*
    - .config/assets/sounds/*
    - .config/assets/ozone/*
    - .config/assets/rgui/*
    - .config/assets/xmb/*
    - -.config/assets/xmb/*/src
    - .config/assets/glui/*.png
    - .config/assets/glui/*.ttf]
    prime: *_assets
  retroarch-autoconfig:
    plugin: dump
    after: [retroarch-assets]
    source: https://github.com/libretro/retroarch-joypad-autoconfig/archive/master.tar.gz
    source-type: tar
    organize:
      udev: .config/autoconfig/udev/
      linuxraw: .config/autoconfig/linuxraw/
      hid: .config/autoconfig/hid/
      x: .config/autoconfig/x/
    stage: &_autoconfig
    - .config/autoconfig/udev
    - .config/autoconfig/linuxraw
    - .config/autoconfig/hid
    - .config/autoconfig/x
    prime: *_autoconfig
  retroarch-database:
    plugin: dump
    after: [retroarch-autoconfig]
    source: https://github.com/libretro/libretro-database/archive/master.tar.gz
    source-type : tar
    organize:
      rdb: .config/database/rdb/
      cursors: .config/database/cursors/
      cht: .config/cheats/
    stage:
      - .config/database
      - .config/cheats
  retroarch-info:
    plugin: dump
    after: [retroarch-database]
    source: https://github.com/libretro/libretro-super/archive/master.tar.gz
    source-type : tar
    organize:
      dist/info: .config/cores/
    stage:
      - .config/cores
  retroarch-overlays:
    plugin: dump
    after: [retroarch-info]
    source: https://github.com/libretro/common-overlays/archive/master.tar.gz
    source-type : tar
    organize:
      "*": .config/overlay/
    stage:
      - .config/overlay
  retroarch-glsl-shaders:
    plugin: dump
    after: [retroarch-overlays]
    source: https://github.com/libretro/glsl-shaders/archive/master.tar.gz
    source-type : tar
    organize:
      "*": .config/shaders/shaders_glsl/
    stage:
      - .config/shaders
  retroarch-slang-shaders:
    plugin: dump
    after: [retroarch-glsl-shaders]
    source: https://github.com/libretro/slang-shaders/archive/master.tar.gz
    source-type: tar
    organize:
      "*": .config/shaders/shaders_slang/
    stage:
      - .config/shaders
  gpu-2404:
    after: [retroarch]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404 nvidia-2404
      rm -rf ${CRAFT_PRIME}/usr/share/{doc,man}
    prime:
      - bin/gpu-2404-wrapper
